import type { Project } from '../../types/project';

export const projects: Project[] = [
  {
    id: 1,
    title: 'Todo list',
    description:
      'Приложение для управления задачами с возможностью добавления, редактирования и удаления задач',
    technologies: [
      'Typescript',
      'React',
      'Tailwind',
      'TanStack Query',
      'Express.js',
    ],
    githubUrl: 'https://github.com/stanislav-sbone/Todo_List',
    demoUrl: 'https://todo-list-sbone.vercel.app/',
    image: '/images/projects/todo-list.png',
    features: [
      'Добавление новых задач',
      'Отметка задач как выполненных/невыполненных',
      'Редактирование задач (с возможностью отмены изменений)',
      'Удаление задач',
      'Фильтрация задач по тексту',
      'Сортировка задач (Все / Выполненные / Невыполненные)',
      'Перетаскивание задач для изменения порядка (drag & drop)',
      'Смена темы (Светлая/Темная) с сохранением в localStorage',
      'Изоляция данных пользователя (через userId)',
      'Адаптивный дизайн',
    ],
  },
  {
    id: 2,
    title: 'Weather App',
    description: 'Приложение прогноза погоды с использованием OpenWeather API',
    technologies: ['Typescript', 'React', 'CSS Modules', 'Axios', 'REST API'],
    githubUrl: 'https://github.com/stanislav-sbone/Weather_App',
    demoUrl: 'https://weather-app-sbone.vercel.app/',
    image: '/images/projects/weather-app.png',
    features: [
      'Вывод текущей погоды с помощью OpenWeather API',
      'Дополнительно вывод прогноза погоды на 5 дней',
      'Адаптивный дизайн',
    ],
  },
  {
    id: 3,
    title: 'Crypto Dashboard',
    description: 'Приложение для просмотра текущих цен на криптовалюту',
    technologies: [
      'Typescript',
      'React',
      'Tailwind',
      'Zustand',
      'TanStack Query',
    ],
    githubUrl: 'https://github.com/stanislav-sbone/CryptoDash',
    image: '/images/projects/crypto-dash.png',
    features: [
      'Просмотр списка популярных Layer-1 криптовалют с текущими ценами и изменением цены за 24 часа',
      'Фильтрация списка криптовалют',
      'Подробная информация о выбранном токене',
      'Актуальные цены, график на 7 дней и данные с CoinGecko API',
      'Смена темы (Тёмная/светлая)',
      'Смена языка приложения (Русский/English)',
    ],
  },
  {
    id: 4,
    title: 'Список героев из аниме Наруто',
    description: 'Приложение для просмотра списка героев из аниме Наруто',
    technologies: ['Typescript', 'React', 'React Router', 'styled-components'],
    githubUrl: 'https://github.com/stanislav-sbone/Naruto',
    demoUrl: 'https://naruto-sbone.vercel.app/',
    image: '/images/projects/naruto-characters.png',
    features: [
      'Вывод персонажей из Наруто из стороннего API',
      'Фильтрация персонажей',
      'Пагинация списка персонажей',
      'Роутинг страниц (Главная, Хвостатые звери, Об аниме)',
      'Отдельные страницы карточек персонажей',
      'Смена темы (Тёмная/светлая)',
    ],
  },
  {
    id: 5,
    title: 'Личный сайт-портфолио',
    description:
      'Сайт визитка с информацией о себе, проектах, контактах и стеке технологий',
    technologies: ['Typescript', 'React', 'CSS Modules', 'React Router'],
    githubUrl: 'https://github.com/stanislav-sbone/Portfolio',
    image: '/images/projects/portfolio.png',
    features: [
      'Навигация по разделам Home / About / Skills / Projects / Contacts без перезагрузки благодаря react-router.',
      'Галерея проектов с карточками и детальными модальными окнами.',
      'Контактная форма с валидацией react-hook-form, уведомлениями react-toastify и отправкой письма через собственный Express API.',
      'Глобальный переключатель темы (light/dark) с сохранением состояния в localStorage.',
      'Адаптивная шапка с бургер-меню',
      'Адаптивный дизайн',
    ],
  },
];
